apiVersion: v1
kind: Pod
metadata:
  name: experiment
spec:
  containers:
    - name: nginx-web
      image: nginx
      ports:
        - containerPort: 8081
      volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx-web.conf
    - name: nginx-experiment
      image: nginx
      ports:
        - containerPort: 8082
      volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx-experiment.conf
    - name: nginx
      image: nginx
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
  volumes:
    - name: config-volume
      configMap:
        name: experiment-config
