apiVersion: v1
kind: Service
metadata:
  name: nginx-service-nodeport
spec:
  type: NodePort
  selector:
    app: nginx-ssl
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30082
