apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-config
data:
  etcd.conf.yml: |
    name: "etcd"
    data-dir: "/var/lib/etcd"
    initial-advertise-peer-urls: "http://etcd-0.etcd:2380"
    listen-peer-urls: "http://0.0.0.0:2380"
    listen-client-urls: "http://0.0.0.0:2379"
    advertise-client-urls: "http://etcd-0.etcd:2379"
    initial-cluster-token: "etcd-cluster"
    initial-cluster: "etcd-0=http://etcd-0.etcd:2380"
    initial-cluster-state: "new"
