apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dictionary-server
spec:
  serviceName: "dictionary-server"
  replicas: 3
  selector:
    matchLabels:
      app: dictionary-server
  template:
    metadata:
      labels:
        app: dictionary-server
    spec:
      containers:
        - name: server
          image: sfktrkl/dictionary-server
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
