apiVersion: v1
kind: Pod
metadata:
  name: adapter
  namespace: default
spec:
  containers:
    - image: mysql
      name: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root_password" # Replace with your root password
        - name: MYSQL_DATABASE
          value: "my_database" # Replace with your database name
        - name: MYSQL_USER
          value: "my_user" # Replace with your non-root username
        - name: MYSQL_PASSWORD
          value: "my_password" # Replace with your non-root password
    - image: sfktrkl/mysql-adapter
      name: adapter
