apiVersion: v1
kind: Service
metadata:
  name: dictionary-server-service-nodeport
spec:
  type: NodePort
  selector:
    app: dictionary-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
