services:
  web:
    image: nginx
    ports:
      - "30080:80"
    container_name: web
  topz:
    image: brendanburns/topz:db0fa58
    command: /server --addr=0.0.0.0:8080
    ports:
      - "8080:8080"
    container_name: topz
    pid: container:web
    depends_on:
      - web
