apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-python
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: sfktrkl/helloworld-python
          ports:
            - containerPort: 8080
