apiVersion: v1
kind: Pod
metadata:
  name: ambassador
spec:
  containers:
    - name: nginx
      image: nginx
    - name: twemproxy
      image: malexer/twemproxy:latest
      command:
        - nutcracker
        - -c
        - /etc/config/nutcracker.yml
        - -v
        - "7"
        - -s
        - "6222"
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: twem-config
