apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluentd.conf: |
    <source>
      @type redis_slowlog
      host localhost
      port 6379
      tag redis.slowlog
    </source>
