apiVersion: v1
kind: Service
metadata:
  name: varnish-service-nodeport
spec:
  type: NodePort
  selector:
    app: varnish-cache
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081
