apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-twemproxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shared-twemproxy
  template:
    metadata:
      labels:
        app: shared-twemproxy
    spec:
      containers:
        - name: twemproxy
          image: malexer/twemproxy:latest
          command:
            - nutcracker
            - -c
            - /etc/config/nutcracker.yml
            - -v
            - "7"
            - -s
            - "6222"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: twem-config
